version: '3'
services:
  app:
    image: altshtern/sce-devops-final-python:latest
    ports:
      - "5000:5000"
    pull_policy: always
    restart: always
    environment:
      - FLASK_ENV=development
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/doc"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app_network:
    driver: bridge