name: CI/CD Pipeline

on:
  push:
    branches:
      - feat/*
  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: self-hosted
    container:
      image: docker:29.1.5-dind
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sce-devops-final-python:latest
  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      # - name: SSH and Deploy
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.REMOTE_HOST }}
      #     username: ${{ secrets.REMOTE_USER }}
      #     key: ${{ secrets.REMOTE_SSH_KEY }}
      #     script: |
      #       docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sce-devops-final-python:latest
      #       docker-compose -f /path/to/your/docker-compose.yml up -d
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Compose changed
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'docker-compose.yml')
        run: echo "Docker Compose file has changed." || docker compose -f docker-compose.yml down

      - name: Docker Compose Deploy
        uses: docker/compose-action@v2
        with:
          compose-file: docker-compose.yml
          args: up -d --pull always