# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Python Package


on:
  workflow_dispatch:


jobs:
  dind-job:
    runs-on: self-hosted

    services:
      docker:
        image: docker:29.1.5-dind
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""
        volumes:
          - /var/lib/docker
    container: docker:20.10.16

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker CLI
        # The main container (which uses ubuntu-latest by default) needs the Docker CLI
        # This step installs the CLI so it can talk to the DinD service
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          
      - name: Build a test image
        # Now Docker commands will use the DinD service
        run: docker build -t test-image .
        
      - name: Run a container from the test image
        run: docker run test-image echo "Docker in Docker works!"
#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python
#       uses: actions/setup-python@v3
#       with:
#         python-version: '3.10'
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install --target=./ -r requirements.txt
      

#     - name: Archive Release
#       uses: thedoctor0/zip-release@0.7.5
#       with:
#         type: 'zip'
#         filename: "package-${{github.ref_name}}.zip"
#         exclusions: '*.git*  .editorconfig'

#     - name: Upload Release
#       uses: ncipollo/release-action@v1.12.0
#       with:
#         artifacts: "package-${{github.ref_name}}.zip"
#         token: ${{ secrets.GITHUB_TOKEN }}
#         allowUpdates: true
#   #    run: python -m build
#   #  - name: Publish package
#   #    uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
#  #     with:
#  #       user: __token__
#  #       password: ${{ secrets.PYPI_API_TOKEN }}
